# 구버전에서는 필요했지만, 더이상 불필요
# version: "3"

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn daniel_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    environment:
      DEBUG: "1"
      SECRET_KEY: "django-insecure-88ndzs0z0uzko4x5f=*ngu=#h+a(k=!#ooyvt*0h+78r1n=^oy"
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=daniel_blog_user
      - POSTGRES_PASSWORD=daniel_blog_db_password
      - POSTGRES_DB=daniel_blog_dev

volumes:
  postgres_data:
  static_volume:
  media_volume: