services:
  web:
    build:
      context: .
    container_name: django_app
    command: gunicorn daniel_blog.wsgi:application --bind 0.0.0.0:8000
#    command: ./wait-for-it.sh db:5432 -- gunicorn daniel_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: daniel_blog_user
      POSTGRES_PASSWORD: daniel_blog_password
      POSTGRES_DB: daniel_blog_db
      SOCIALAPP_CLIENT_ID: 144736340574-a4fukokks5u4jt82v4gnifkka03t0542.apps.googleusercontent.com
      SOCIALAPP_SECRET: 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
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: daniel_blog_user
      POSTGRES_PASSWORD: daniel_blog_password
      POSTGRES_DB: daniel_blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    image: nginx:1.27
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: daniel_blog_app-network
    driver: bridge