[build]
  command = "pip install --upgrade pip setuptools && pip install --no-cache-dir -r requirements.txt && python manage.py collectstatic --noinput && npm run build"
  publish = "build"

[context.production.environment]
  PYTHON_VERSION = "3.10"

[build.environment]
  PYTHON_VERSION = "3.10"
